CREATE TABLE xxl_job_info (
    id BIGINT NOT NULL AUTO_INCREMENT,
    job_group INT NOT NULL,
    job_desc VARCHAR(255) NOT NULL,
    add_time DATETIME,
    update_time DATETIME,
    author VARCHAR(64),
    alarm_email VARCHAR(255),
    schedule_type VARCHAR(50) NOT NULL DEFAULT 'NONE',
    schedule_conf VARCHAR(128),
    misfire_strategy VARCHAR(50) NOT NULL DEFAULT 'DO_NOTHING',
    executor_route_strategy VARCHAR(50),
    executor_handler VARCHAR(255),
    executor_param VARCHAR(512),
    executor_block_strategy VARCHAR(50),
    executor_timeout INT NOT NULL DEFAULT 0,
    executor_fail_retry_count INT NOT NULL DEFAULT 0,
    glue_type VARCHAR(50) NOT NULL,
    glue_source TEXT,
    glue_remark VARCHAR(128),
    glue_updatetime DATETIME,
    child_jobid VARCHAR(255),
    trigger_status TINYINT NOT NULL DEFAULT 0,
    trigger_last_time BIGINT NOT NULL DEFAULT 0,
    trigger_next_time BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);